# Site settings
title: 8D is Here
email: i@xiaoba.me
author: Yuwei Ba
meta: 天青色等烟雨，而我在等你。
description: Programming makes life easier and better. Life Lover.
keywords: Javascript, Python, Life, Thoughts
favicon: /favicon.png
baseurl: ""
url: http://blog.xiaoba.me
comments: true
disqus: heheblog
analytics: true
ga: UA-53224060-1
cdn: http://yuwei-cdn.b0.upaiyun.com/blog/images

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title.html
